Repository APP-iOS3rd/PJ2T1_WeatherPlaylist, pull requests merged in 2023-12, with the labels that each got.

#1 [Feat]:mypage 마이페이지 뷰 구현
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Assets.xcassets/emptyImg.imageset/Contents.json
  WeatherPlaylist/WeatherPlaylist/Assets.xcassets/emptyImg.imageset/emptyImg.png
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/String+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/UIImage+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/WeatherLogic.swift
  WeatherPlaylist/WeatherPlaylist/Source/ViewModifier/ImageModifier.swift
  WeatherPlaylist/WeatherPlaylist/Views/ContentView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageSubView/PlaylistScrollView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageSubView/ProfileView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/PlaylistModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/ProfileModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/ProfileViewModel.swift
Labels: Feature

#2 Pretendard 추가하기
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Font/Font+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-Black.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-Bold.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-ExtraBold.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-ExtraLight.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-Light.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-Medium.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-Regular.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-SemiBold.otf
  WeatherPlaylist/WeatherPlaylist/Font/Pretendard-Thin.otf
  WeatherPlaylist/WeatherPlaylist/Info.plist
Labels: Feature

#7 [Feat]: PlaylistView 구현
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/Alignment+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/HorizontalAlignment+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/VerticalAlignment+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Views/ContentView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistControllerView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistCorverImageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistRowView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistStickyHeader.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistViewModel.swift
Labels: Feature

#11 Refactoring/view connect 뷰 연결 구현하기
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/Font+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/UIImage+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Source/Extensions/UIkit+Extensions.swift
  WeatherPlaylist/WeatherPlaylist/Views/Components/BottomDrawer/BottomDrawer.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlayMusicView/HeaderView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlayMusicView/PlayMusicView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistControllerView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistCorverImageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistRowView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistStickyHeader.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistViewModel.swift
  WeatherPlaylist/WeatherPlaylist/WeatherPlaylistApp.swift
Labels: Refactoring

#26 Feat/Weather API 관련 기초 작업 완료
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Preview Content/ApiKeys.plist
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/Weather/LocationManager.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/Weather/Model/WeatherModel.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/Weather/WeatherAPI.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/Weather/WeatherLogic.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/Weather/WeatherTestView.swift
Labels: Feature

#30 Feat/refresh token 토큰리프레시와 마이페이지
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Info.plist
  WeatherPlaylist/WeatherPlaylist/Models/NetworkDTO/UserInfoResponse.swift
  WeatherPlaylist/WeatherPlaylist/Models/NetworkDTO/UserPlaylistDTO.swift
  WeatherPlaylist/WeatherPlaylist/Models/RecommendedPlayListModel.swift
  WeatherPlaylist/WeatherPlaylist/Models/UserInformationModel.swift
  WeatherPlaylist/WeatherPlaylist/Resource/Launch Screen.storyboard
  WeatherPlaylist/WeatherPlaylist/Source/APIProtocol.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainViewModel/MainPageViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageSubView/PlaylistScrollView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageSubView/ProfileView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/ProfileModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/ProfileViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartSubViews/AuthView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartSubViews/LoginView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartViewModel.swift
Labels: Feature

#32 Feat/mini music player
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Models/NetworkDTO/UserInfoResponse.swift
  WeatherPlaylist/WeatherPlaylist/Models/NetworkDTO/UserPlaylistResponse.swift
  WeatherPlaylist/WeatherPlaylist/Source/APIProtocol.swift
  WeatherPlaylist/WeatherPlaylist/Views/Components/PlayFooterCell/PlayFooterCell.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainViewModel/MainPageViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/PlaylistVertical.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/ProfileViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/RootView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartSubViews/LoginView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartView.swift
Labels: Refactoring

#33 Feat/mini music player
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/Weather/WeatherLogic.swift
  WeatherPlaylist/WeatherPlaylist/Views/Components/PlayFooterCell/PlayFooterCell.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainViewModel/MainPageViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/ProfileViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/TempPlaylistModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlayMusicView/PlayMusicListModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlayMusicView/PlayMusicViewModel.swift
Labels: Feature, Refactoring

#34 [Feat]: 로그인 기능 구현
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Views/MypageView/MyPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartSubViews/AuthView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartSubViews/LoginView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartView.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartViewModel.swift
  WeatherPlaylist/WeatherPlaylist/WeatherPlaylistApp.swift
Labels: Feature

#35 Refactoring/view refactoring
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Models/NetworkDTO/TrackListResponse.swift
  WeatherPlaylist/WeatherPlaylist/Models/NetworkDTO/UserInfoResponse.swift
  WeatherPlaylist/WeatherPlaylist/Models/RecommendedPlayListModel.swift
  WeatherPlaylist/WeatherPlaylist/Source/APIProtocol.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/HapticManager.swift
  WeatherPlaylist/WeatherPlaylist/Source/Singleton/SigningManager.swift
  WeatherPlaylist/WeatherPlaylist/Source/UserRequest.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainPageView.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/MainViewModel/MainPageViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/MainView/PlaylistVertical.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlayMusicView/PlayMusicViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistControllerView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistSubView/PlaylistStickyHeader.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistView.swift
  WeatherPlaylist/WeatherPlaylist/Views/PlaylistView/PlaylistViewModel.swift
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartViewModel.swift
Labels: Feature, Refactoring

#42 [hotfix]: 네이버로 이동하는 오류 수정
  WeatherPlaylist/WeatherPlaylist.xcodeproj/project.pbxproj
  WeatherPlaylist/WeatherPlaylist/Views/StartView/StartSubViews/AuthView.swift
Labels: Bug, Refactoring
